<a href="https://colab.research.google.com/github/dmdwn99/Computer-Vision-Study/blob/main/Computer_vision_study_Week_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Tensorflow 2.0

In [11]:
# 텐서플로 버전 2.x 선택하기
try:
  %tensorflow_version 2.x
except Exception:
  pass
import tensorflow as tf
print(tf.__version__)

2.8.0


# 2. Tensorflow 기초

랜덤은 신경망에서 필수 기능

신경망: 많은 숫자로 구성된 행렬

초기화: 신경망의 초기값을 지정해주는 것

Xavier 초기화, He 초기화가 자주 사용됨

In [21]:
# 난수 생성
rand = tf.random.uniform([1],0,1) # 균일 분포 난수 생성
# 균일 분포란 최솟값, 최댓값 사이의 모든 수가 나올 확률이 동일한 분포에서 수를 뽑는 것
print(rand)

tf.Tensor([0.40707147], shape=(1,), dtype=float32)


In [22]:
rand = tf.random.uniform([4],0,1)
print(rand)

tf.Tensor([0.5748664  0.5799935  0.31368542 0.5109875 ], shape=(4,), dtype=float32)


In [23]:
# 정규분포
rand = tf.random.normal([4],0,1)
print(rand)

tf.Tensor([-0.11001303  0.23434742 -1.665555   -0.5492535 ], shape=(4,), dtype=float32)


In [ ]:
# 뉴런 만들기
# 신경망: 뉴련이 여러개 모여 레이어를 구성한 후 레이어를 다시 모아 구성한 형태
# 뉴련은 입력, 가중치, 활성화함수, 출력으로 구성
# 활성화 함수: 시그모이드, ReLU가 자주 사용됨
# 은닉층: 신경망에서 입력층과 출력층을 제외한 나머지 부분을 은닉층. 가중치와 활성화 함수로 구성
# 초창기에는 시그모이드가 주로 쓰였지만 은닉층을 다수 사용하는 딥러닝 시대가 되면서 ReLU가 더 많이 쓰임


In [24]:
import math
def sigmoid(x):
  return 1/ (1+math.exp(-x))

In [34]:
x = 1
y = 0
w = tf.random.normal([1],0,1)
output = sigmoid(x * w)
print(output)

0.5540523885718102


In [36]:
for i in range(1000):
  output = sigmoid(x * w)
  error = y - output
  w = w + x * 0.1 * error

  if i % 100 == 99:
    print(i, error, output)

99 -0.10595287173158083 0.10595287173158083
199 -0.05339021831160849 0.05339021831160849
299 -0.035312689739303994 0.035312689739303994
399 -0.026295676417921098 0.026295676417921098
499 -0.020917793400284882 0.020917793400284882
599 -0.017353541891795166 0.017353541891795166
699 -0.014820776606474755 0.014820776606474755
799 -0.012929713883323212 0.012929713883323212
899 -0.01146451609226613 0.01146451609226613
999 -0.010296291288623957 0.010296291288623957


In [37]:
# 입력 0, 출력 1 뉴런
x = 0
y = 1
w = tf.random.normal([1],0,1)
for i in range(1000):
  output = sigmoid(x * w)
  error = y - output
  w = w * x + 0.1 * error

  if i % 100 == 99:
    print(i, error, output)

99 0.5 0.5
199 0.5 0.5
299 0.5 0.5
399 0.5 0.5
499 0.5 0.5
599 0.5 0.5
699 0.5 0.5
799 0.5 0.5
899 0.5 0.5
999 0.5 0.5


In [40]:
# 편향(bias) 추가
x = 0
y = 1
w = tf.random.normal([1],0,1)
b = tf.random.normal([1],0,1)

for i in range(1000):
  output = sigmoid(x * w + 1 * b)
  error = y - output
  w = w + x * 0.1 * error
  b = b + 1 * 0.1 * error

  if i % 100 == 99:
    print(i, error, output)

99 0.11233633850084301 0.887663661499157
199 0.055060115537330145 0.9449398844626699
299 0.03604941135075379 0.9639505886492462
399 0.0267057996110871 0.9732942003889129
499 0.021177891327152754 0.9788221086728472
599 0.017532803435301725 0.9824671965646983
699 0.014951670960649865 0.9850483290393501
799 0.013029396832063056 0.9869706031679369
899 0.011542943987083665 0.9884570560129163
999 0.010359573544649447 0.9896404264553506


# 3. 신경망 네트워크: AND




In [42]:
# AND 연산 수행 뉴런
import numpy as np
x = np.array([[1,1],[1,0],[0,1],[0,0]])
y = np.array([[1],[0],[0],[0]])
w = tf.random.normal([2],0,1)
b = tf.random.normal([1],0,1)
b_x = 1

for i in range(2000):
  error_sum = 0
  for j in range(4):
    output = sigmoid(np.sum(x[j]*w)+b_x*b)
    error = y[j][0] - output
    w = w * x[j] * 0.1 * error
    b = b * b_x * 0.1 * error
    error_sum += error_sum
  if i % 200 == 199:
    print(i, error_sum)

199 0
399 0
599 0
799 0
999 0
1199 0
1399 0
1599 0
1799 0
1999 0
